server.servlet.context-path: /spring-security-oauth-server
server.port: 8081
logging:
  level:
    org:
      apache:
        http:
          wire: debug
      springframework:
        cloud:
          netflix: trace

server:
  tomcat:
    accesslog:
      enabled: true
server.tomcat.accesslog.directory: /dev
server.tomcat.accesslog.prefix: stdout
server.tomcat.accesslog.buffered: false

# Don't use empty double quotes, see below
#server.tomcat.accesslog.suffix: asd
#server.tomcat.accesslog.file-date-format:
server.tomcat.accesslog.suffix: ""
server.tomcat.accesslog.file-date-format: ""

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl.auto: validate
        show_sql: true
        format_sql: true
  flyway:
    enabled: true
#    schemas: chrg2
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=chrg2
    #    url: jdbc:postgresql://193.48.96.91:5432/rdbo?currentSchema=chrg
#    user: postgres
    #    user: rdbo_chrg_cd
#    password: postgres
  #    password: qwe1234rty
#server.tomcat.basedir=/var/tomcat
#server.tomcat.accesslog.buffered: true
#server.tomcat.accesslog.directory: access/log
#server.tomcat.accesslog.enabled: true
#server.tomcat.accesslog.pattern: "%h %{X-Forwarded-For}i %l %u %t %r %s %b"
#server.tomcat.accesslog.prefix: tomcat_access_log
#Metrics related configurations
management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: "*"
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true